### ISSUE TITLE
How to set nullable integer column into null ?

### ISSUE THREAD

**Issue by zesagata** [SoftwareBrothers/admin-bro-typeorm#7]
Hi guys, I wanna ask something

I have column something like this
```typescript
@Column({ default: 100, nullable: true  })
columnA: number | null
```
and i already create validation at `actions.edit.before`  like this
```typescript
async function handleNullColumnA(request: any) {
  const { payload } = request
  if (payload.columnA=== 'null' || payload.columnA=== 'NULL') {
    payload.columnA= null
  }
  return request
}
```

But its always updated into `0` because of this [line of code](https://github.com/SoftwareBrothers/admin-bro-typeorm/blob/f60e61ddc6fe3b510457e571df982ec37cf1eb12/src/Resource.ts#L171)

Any idea how solve this ?

**Comment by wojtek-krysiak** [comment]
in before action hook you can strip payload from this property

**Comment by zesagata** [comment]
@wojtek-krysiak  thank you sir for your response, its work !
```typescript
async function handleNullColumnA(request: any, context: any) {
  const { payload } = request
  if (payload.columnA=== 'null' || payload.columnA=== 'NULL') {
    delete context?.resource?.propsObject.columnA
    payload.columnA= null
  }
  return request
}
```
